run:
  deadline: 2m
  issues-exit-code: 1
  tests: true
  modules-download-mode: vendor

# output configuration options
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

# all available settings of specific linters
linters-settings:
  dupl:
    threshold: 100
  errcheck:
    check-type-assertions: false
    check-blank: true
  funlen:
    lines: 60
    statements: 60
  gocognit:
    min-complexity: 20
  goconst:
    min-len: 3
    min-occurrences: 3
  gocyclo:
    min-complexity: 20
  gofmt:
    simplify: true
  goimports:
  gomnd:
    settings:
      mnd:
        # the list of enabled checks, see https://github.com/tommy-muehle/go-mnd/#checks for description.
        checks: argument
  govet:
    check-shadowing: true
  maligned:
    suggest-new: false
  misspell:
    locale: US
  nakedret:
    max-func-lines: 30
  nolintlint:
    allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped
  lll:
    line-length: 120
    tab-width: 1
  unparam:
    check-exported: false
  unused:
    check-exported: false

  gocritic:
    enabled-checks:
      - appendAssign
      - appendCombine
      - assignOp
      - boolExprSimplify
      - builtinShadow
      - captLocal
      - caseOrder
      - defaultCaseOrder
      - dupArg
      - dupBranchBody
      - dupCase
      - dupSubExpr
      - elseif
      - emptyFallthrough
      - emptyStringTest
      - flagDeref
      - flagName
      - hexLiteral
      - ifElseChain
      - importShadow
      - indexAlloc
      - methodExprCall
      - nestingReduce
      - nilValReturn
      - offBy1
      - ptrToRefParam
      - regexpMust
      - singleCaseSwitch
      - sloppyLen
        #- sloppyReassign
      - switchTrue
      - typeAssertChain
      - typeSwitchVar
      - typeUnparen
      - underef
      - unlambda
      - unnecessaryBlock
      - unslice
      - valSwap
      - wrapperFunc
      - yodaStyleExpr

issues:
  exclude-use-default: true
  max-per-linter: 0
  max-same-issues: 0
  new: false
  #new-from-rev: "HEAD~1"
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec

# linters that we should / shouldn't run
linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - lll
    - maligned
    - prealloc
    - godox
    - gomnd
    - testpackage
    - godot
    - goerr113
    - interfacer
    - noctx
    - goheader
    - nlreturn
    - gci
    - exhaustivestruct
    - errorlint
    - tparallel
    - wrapcheck
    - paralleltest
    - forbidigo
    - makezero
    - thelper
    - cyclop
    - importas
    - gomoddirectives
    - promlinter
    - tagliatelle
    - varnamelen
    - funlen
    - scopelint
    - gocognit
    - golint
