linters:
  enable:
    - errname
    - exhaustive
    - gci
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - godot
    - gofumpt
    - goheader
    - goimports
    - gosec
    - ifshort
    - importas
    - ireturn
    - revive
