name: CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-20.04', 'macos-latest', 'windows-latest']
        go: [ '1.16', '1.17' ]
    runs-on: ${{ matrix.os }}

    name: Build (Go ${{ matrix.go }}, OS ${{ matrix.os }})
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - name: go test -v ./...
      run: go test -v ./...
