name: CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  fixtures:
    name: fixtures-up-to-date
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v17
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    - name: Install the environment
      run: nix-env -f nix -A env -i
    - name: Build fixtures
      run: just fixtures
    - name: Diff fixtures
      run: git diff --exit-code test/testdata

  protos-up-to-date:
    name: protos-up-to-date
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v17
    - name: Install the environment
      run: nix-env -f nix -A env -i
    - name: Buf lint
      run: just proto-lint
    - name: Buf generate
      run: just proto-generate
    - name: Diff protos
      run: git diff --exit-code

  build:
    strategy:
      matrix:
        os: ['ubuntu-20.04', 'macos-latest', 'windows-latest']
        go: [ '1.17', '1.18' ]
    runs-on: ${{ matrix.os }}

    name: Build (Go ${{ matrix.go }}, OS ${{ matrix.os }})
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - name: go test and bench
      run: just bench
