name: go-test

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: [ '1.14', '1.15', '1.16' ]
    name: Build (Go ${{ matrix.go }})
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - name: go test -v ./...
      run: go test -v ./...
